name: Code Quality Validation

# Workflow temporarily disabled
on:
  push:
    branches:
      - disabled_branch_name_that_doesnt_exist
  pull_request:
    branches:
      - disabled_branch_name_that_doesnt_exist

# Original configuration (commented out for reference)
# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Run fixture and mapping validation
      run: npm run validate
      
    - name: Run ESLint
      run: npm run lint
      continue-on-error: true
      
    - name: Run tests
      run: npm test 